sudo: false
language: node_js
branches:
  only:
  - master
addons:
  apt:
    packages:
    - sshpass
before_install: true
install: true
before_script:
- chmod +x ./deploy/deploy.sh
script: true
after_script: "./deploy/deploy.sh"
env:
  secure: 1onE/JeFbUKbmC7aEuM53f8NFSVMsu+dn4Pl/tRvPQLsrZBBAr1vGwTC/oh3UcXznIQdgcBWDd2v8IAJUqmEy9NzSzlwmUxrMvEDbed5U+IcV2VPeRyfc0IkgPDMOl8wJDyldgXuxPUpN9AZ4ZvEzwWg1zxNVI6LikrxKK9NxNvvsqJlmyIaYmW5mCSLppgfFCWTaHBgLDvcbkJUpXEVi8sjLl2PeIiSMtyBJgAwLt17KxlCfC/d6+U9G8JYlF3zgPsdCNogXNnOVKti6LG1cZIvc+ifeejdEg3jiXAxMj4gJG9N2mI+8+SfMks7HRnX8ornTFd+h9eMZTYobJ16oeQF6eMzHUST/SrYw2PfYiB9+vLiSEU1IkG+uzxDuiHT9K0tpuZfYGdQIbqR+yD9HxWF83+VUTfQL01Xq2j8zGJ+x4YZceqBfMSMecxb8NhEGf/+BIG47cgafkDcPfdJU6sZwumor7kcsgHfA9XNBsBQl9pKoQYLPi7gOiJgCbFcivDDl2CL48keO9m/t8uqfEPz6ol2pr1g+/kBvlm269sFV6quOpkvxkn4W2RyfdL6NcSctDS3eq72uwxHP/Df0v6ifGZ7JJPi8Warxv8i5KOr1Squc/1emJk4KAvLGrEYW5EmiQbmJenax5R+nixorGt28n5wAYsWLLkIrzip9wY=
